BlogApp/urls.py
from django.urls import path
from . import views

app_name = "BlogApp"
urlpatterns = [
    path("browse", views.browse, name="browse"),
    path("add_blog", views.add_blog, name="add_blog"),
    path("edit_blog/<int:blog_id>", views.edit_blog, name="edit_blog"),
    path("delete_blog/<int:blog_id>", views.delete_blog, name="delete_blog"),
    path("like/<int:blog_id>/", views.like_blog, name="like_blog"),
    path("comment/<int:blog_id>/", views.add_comment, name="add_comment"),
]

MyAuth/urls.py
from django.urls import path
from . import views

app_name = "MyAuth"
urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.login_user, name="login_user"),
    path("logout/", views.logout_user, name="logout_user"),
    path("register/", views.register_user, name="register_user"),
]

MyBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("MyAuth.urls")),
    path("blog/", include("BlogApp.urls")),
]

MyAuth/models.py
from django.db import models

# Create your models here.

MyAuth/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


def home(request):
    return render(request, "MyAuth/home.html", {})


def login_user(request):
    if request.method == "GET":
        form = AuthenticationForm()
        return render(
            request,
            "MyAuth/login.html",
            {
                "form": form,
            },
        )
    elif request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username, password = form.cleaned_data.get(
                "username"
            ), form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "Logged In!")
                return redirect(reverse("MyAuth:home"))
            else:
                messages.error(request, "Invalid Username or Password.")
                return redirect(reverse("MyAuth:login_user"))
        else:
            messages.error(request, "Invalid Form Fields.")
            return redirect(reverse("MyAuth:login_user"))


@login_required
def logout_user(request):
    logout(request)
    messages.success(request, "Logged Out!")
    return redirect(reverse("MyAuth:home"))


def register_user(request):
    if request.method == "GET":
        form = UserCreationForm()
        return render(
            request,
            "MyAuth/register.html",
            {
                "form": form,
            },
        )
    elif request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username, password = form.cleaned_data.get(
                "username"
            ), form.cleaned_data.get("password1")
            user = authenticate(request, username=username, password=password)
            login(request, user)
            messages.success(request, "Registered!")
            return redirect(reverse("MyAuth:home"))
        else:
            messages.error(request, "Invalid Username or Password.")
            return redirect(reverse("MyAuth:register_user"))

MyAuth/templates/MyAuth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>MyBlog: {% block title %}{% endblock %}</title>
</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>

MyAuth/templates/MyAuth/home.html
{% extends "MyAuth/base.html" %}

{% block title %}
    Home
{% endblock %}
 

{% block body %}
    <div class="container mt-4">
        <h3>Welcome to Our Blogging Platform!</h3>
        
        <p>Explore a world of diverse perspectives and engaging content created by our community of writers.</p>
        
        {% if messages %}
            <div class="alert alert-info">
                {% for msg in messages %}
                    {{ msg }}
                {% endfor %}
            </div>
        {% endif %}

        <ul class="list-unstyled">
            {% if user.is_authenticated %}
                <li class="mb-3"><a href="{% url 'BlogApp:browse' %}" class="btn btn-secondary">Browse Blogs</a></li>
                <li class="mb-3"><a href="{% url 'MyAuth:logout_user' %}" class="btn btn-danger">Logout Here</a></li>
            {% else %}
                <li class="mb-3"><a href="{% url 'MyAuth:login_user' %}" class="btn btn-success">Login Here</a></li>
                <li class="mb-3"><a href="{% url 'MyAuth:register_user' %}" class="btn btn-primary">Register Here</a></li>
            {% endif %}
        </ul>
    </div>
{% endblock %}

MyAuth/templates/MyAuth/login.html
{% extends "MyAuth/base.html" %}

{% block title %}
    Login
{% endblock %}
 

{% block body %}
    <div class="container mt-4">
        {% if messages %}
            <div class="alert alert-info">
                {% for msg in messages %}
                    {{ msg }}
                {% endfor %}
            </div>
        {% endif %}

        <form action="{% url 'MyAuth:login_user' %}" method="post" class="needs-validation" novalidate>
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.help_text %}
                        <small id="{{ field.id_for_label }}Help" class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                        <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
{% endblock %}

MyAuth/templates/MyAuth/register.html
{% extends "MyAuth/base.html" %}

{% block title %}
    Register
{% endblock %}
 

{% block body %}
    <div class="container mt-4">
        {% if messages %}
            <div class="alert alert-info">
                {% for msg in messages %}
                    {{ msg }}
                {% endfor %}
            </div>
        {% endif %}

        <form action="{% url 'MyAuth:register_user' %}" method="post" class="needs-validation" novalidate>
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.help_text %}
                        <small id="{{ field.id_for_label }}Help" class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                        <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
{% endblock %}